/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Web_Service_CEP.WebServiceCep;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.pojo.Cliente;
import model.pojo.Estado;
import model.dao.ClienteDAO;
import model.dao.EstadoDAO;


/**
 *
 * @author Usuario
 */
public class Cadastro_de_Clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cadastro_de_Clientes
     */
    public Cadastro_de_Clientes() {
        initComponents();
        seta_Botoes();
        readJTable();
        readComboUf();
        desativa_Campos();
           }
    int flag = -1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        painelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        painelTabela = new javax.swing.JPanel();
        lblClientesCadastrados = new javax.swing.JLabel();
        jftxtPesquisa = new javax.swing.JFormattedTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        pnlGuias = new javax.swing.JTabbedPane();
        painelDadosp = new javax.swing.JPanel();
        btnAvançar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblData_Nasc = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        jftxtData_Nasc = new javax.swing.JFormattedTextField();
        jftxtCpf = new javax.swing.JFormattedTextField();
        jftxtRg = new javax.swing.JFormattedTextField();
        ComboSexo = new javax.swing.JComboBox<>();
        lblSexo = new javax.swing.JLabel();
        lblTelFixo = new javax.swing.JLabel();
        jftxtTelFixo = new javax.swing.JFormattedTextField();
        lblTelCel = new javax.swing.JLabel();
        jftxtTelCel = new javax.swing.JFormattedTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblCnpj = new javax.swing.JLabel();
        jftxtCnpj = new javax.swing.JFormattedTextField();
        comboPessoa = new javax.swing.JComboBox<>();
        lblPessoa = new javax.swing.JLabel();
        lblContato = new javax.swing.JLabel();
        txtContato = new javax.swing.JTextField();
        painelDadosr = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        lblCep = new javax.swing.JLabel();
        jftxtCep = new javax.swing.JFormattedTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        ComboUF = new javax.swing.JComboBox<>();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastro de Clientes");
        setToolTipText("");
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);

        painelBotoes.setBackground(new java.awt.Color(204, 204, 204));
        painelBotoes.setOpaque(false);

        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnNovo)
                .addGap(5, 5, 5)
                .addComponent(btnExcluir)
                .addGap(5, 5, 5)
                .addComponent(btnSalvar)
                .addGap(5, 5, 5)
                .addComponent(btnCancelar)
                .addGap(5, 5, 5)
                .addComponent(btnSair))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo)
                    .addComponent(btnExcluir)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnSair)))
        );

        painelTitulo.setBackground(new java.awt.Color(204, 204, 204));
        painelTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelTitulo.setOpaque(false);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setText("Cadastro de Clientes");

        javax.swing.GroupLayout painelTituloLayout = new javax.swing.GroupLayout(painelTitulo);
        painelTitulo.setLayout(painelTituloLayout);
        painelTituloLayout.setHorizontalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblTitulo))
        );
        painelTituloLayout.setVerticalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelTabela.setBackground(new java.awt.Color(204, 204, 204));
        painelTabela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelTabela.setOpaque(false);

        lblClientesCadastrados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblClientesCadastrados.setText("Clientes Cadastrados");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome", "Telefone Fixo", "Telefone Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.setOpaque(false);
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        tblClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblClientesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Pesquisa Avançada: ");

        javax.swing.GroupLayout painelTabelaLayout = new javax.swing.GroupLayout(painelTabela);
        painelTabela.setLayout(painelTabelaLayout);
        painelTabelaLayout.setHorizontalGroup(
            painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTabelaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTabelaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblClientesCadastrados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        painelTabelaLayout.setVerticalGroup(
            painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTabelaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jftxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(lblClientesCadastrados)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlGuias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlGuias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        painelDadosp.setBackground(new java.awt.Color(204, 204, 204));
        painelDadosp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelDadosp.setOpaque(false);

        btnAvançar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAvançar.setText("Avançar");
        btnAvançar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvançarActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNome.setText("Nome: ");

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        lblData_Nasc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblData_Nasc.setText("Nascimento: ");

        lblCpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCpf.setText("Cpf: ");

        lblRg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRg.setText("Rg:  ");

        try {
            jftxtData_Nasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("**/**/****")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftxtData_Nasc.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        try {
            jftxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("***.***.***-**")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftxtCpf.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        try {
            jftxtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("**.***.***-**")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftxtRg.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        ComboSexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino" }));
        ComboSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSexoActionPerformed(evt);
            }
        });

        lblSexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSexo.setText("Sexo: ");

        lblTelFixo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelFixo.setText("Tel. Fixo:  ");

        try {
            jftxtTelFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(**)****-****")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftxtTelFixo.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        lblTelCel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelCel.setText("Tel. Celular:  ");

        try {
            jftxtTelCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(**)*****-****")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftxtTelCel.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jftxtTelCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxtTelCelActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setText("Email: ");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblCnpj.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCnpj.setText("Cnpj: ");

        try {
            jftxtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("**.***.***/****-**")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftxtCnpj.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jftxtCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxtCnpjActionPerformed(evt);
            }
        });

        comboPessoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Física", "Jurídica" }));
        comboPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPessoaActionPerformed(evt);
            }
        });

        lblPessoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPessoa.setText("Pessoa: ");

        lblContato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblContato.setText("Contato: ");

        txtContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDadospLayout = new javax.swing.GroupLayout(painelDadosp);
        painelDadosp.setLayout(painelDadospLayout);
        painelDadospLayout.setHorizontalGroup(
            painelDadospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadospLayout.createSequentialGroup()
                .addGroup(painelDadospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadospLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblNome)
                        .addGap(8, 8, 8)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadospLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblPessoa)
                        .addGap(10, 10, 10)
                        .addComponent(comboPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblData_Nasc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftxtData_Nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(lblRg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftxtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadospLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblCpf)
                        .addGap(11, 11, 11)
                        .addComponent(jftxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lblCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jftxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblSexo)
                        .addGap(2, 2, 2)
                        .addComponent(ComboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadospLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(painelDadospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelFixo)
                            .addGroup(painelDadospLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jftxtTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(lblTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jftxtTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(painelDadospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContato, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelDadospLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painelDadospLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(btnAvançar)))
                .addGap(20, 20, 20))
        );
        painelDadospLayout.setVerticalGroup(
            painelDadospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadospLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(painelDadospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadospLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblNome))
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(painelDadospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPessoa)
                        .addComponent(comboPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblData_Nasc)
                        .addComponent(jftxtData_Nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRg)
                        .addComponent(jftxtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(painelDadospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelDadospLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(painelDadospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCpf)
                            .addComponent(lblCnpj)
                            .addComponent(lblSexo))))
                .addGap(20, 20, 20)
                .addGroup(painelDadospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftxtTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftxtTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelDadospLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(painelDadospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelFixo)
                            .addComponent(lblTelCel)
                            .addComponent(lblContato))))
                .addGap(20, 20, 20)
                .addGroup(painelDadospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadospLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvançar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlGuias.addTab("Dados Pessoais", painelDadosp);

        painelDadosr.setBackground(new java.awt.Color(204, 204, 204));
        painelDadosr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelDadosr.setOpaque(false);

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setMaximumSize(new java.awt.Dimension(79, 23));
        btnVoltar.setMinimumSize(new java.awt.Dimension(79, 23));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblCep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCep.setText("Cep: ");

        try {
            jftxtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*****-***")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftxtCep.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jftxtCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftxtCepFocusLost(evt);
            }
        });
        jftxtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxtCepActionPerformed(evt);
            }
        });
        jftxtCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftxtCepKeyPressed(evt);
            }
        });

        lblEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEndereco.setText("Endereço: ");

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        lblNumero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNumero.setText("Numero: ");

        lblUF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUF.setText("UF: ");

        ComboUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        lblCidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCidade.setText("Cidade: ");

        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        lblComplemento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblComplemento.setText("Complemento: ");

        txtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDadosrLayout = new javax.swing.GroupLayout(painelDadosr);
        painelDadosr.setLayout(painelDadosrLayout);
        painelDadosrLayout.setHorizontalGroup(
            painelDadosrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosrLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblCep)
                .addGap(9, 9, 9)
                .addComponent(jftxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblEndereco)
                .addGap(6, 6, 6)
                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(painelDadosrLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblNumero)
                .addGap(5, 5, 5)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblUF)
                .addGap(8, 8, 8)
                .addComponent(ComboUF, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblCidade)
                .addGap(11, 11, 11)
                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(painelDadosrLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblComplemento)
                .addGap(7, 7, 7)
                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(painelDadosrLayout.createSequentialGroup()
                .addGap(478, 478, 478)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelDadosrLayout.setVerticalGroup(
            painelDadosrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosrLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(painelDadosrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelDadosrLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(painelDadosrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCep)
                            .addComponent(lblEndereco))))
                .addGap(20, 20, 20)
                .addGroup(painelDadosrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboUF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelDadosrLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(painelDadosrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumero)
                            .addComponent(lblUF)
                            .addComponent(lblCidade))))
                .addGap(20, 20, 20)
                .addGroup(painelDadosrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosrLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblComplemento))
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlGuias.addTab("Endereço", painelDadosr);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlGuias)
            .addComponent(painelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGuias, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Verifica_Pessoa(){
        if(comboPessoa.getSelectedIndex()==0){
            
            jftxtData_Nasc.setEnabled(true);
            jftxtRg.setEnabled(true);
            jftxtCpf.setEnabled(true);
            jftxtCnpj.setEnabled(false);
            ComboSexo.setEnabled(true);
            txtContato.setEnabled(false);
        }
        else if(comboPessoa.getSelectedIndex()==1){
            jftxtData_Nasc.setEnabled(false);
            jftxtRg.setEnabled(false);
            jftxtCpf.setEnabled(false);
            jftxtCnpj.setEnabled(true);
            ComboSexo.setEnabled(false);
            txtContato.setEnabled(true);
        }
    }
    
    //MÉTODO QUE LIMPA TODOS OS CAMPOS DA TELA DE CADASTRO
    public void Limpa_Campos(){
        txtNome.setText("");
        jftxtData_Nasc.setText("");
        jftxtRg.setText("");
        jftxtCpf.setText("");
        jftxtCnpj.setText("");
        ComboSexo.setSelectedItem("Selecione");
        jftxtTelFixo.setText("");
        jftxtTelCel.setText("");
        txtEmail.setText("");
        jftxtCep.setText("");
        txtEndereco.setText("");
        txtNumero.setText("");
        ComboUF.setSelectedItem("Selecione");
        txtCidade.setText("");
        txtComplemento.setText("");
    }
    
    //MÉTODO PARA HABILITAR OU DESABILITAR BOTÕES
    public void seta_Botoes(){
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
    }
    
    //MÉTODO QUE POPULA A TABELA DE CLIENTES COM OS DADOS DO BANCO DE DADOS
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
        modelo.setNumRows(0);
        ClienteDAO clientedao =  new ClienteDAO();
        
        for(Cliente cliente: clientedao.read()){
            modelo.addRow(new Object[]{
                cliente.getId(),
                cliente.getNome(),
                cliente.getTel_fixo(),
                cliente.getTel_cel()
            });
        }
        SetaLargura_Jtable();
    }
    
    //MÉTODO QUE SETA A LARGURA DOS CAMPOS DA TABELA DOS CLIENTES
    public void SetaLargura_Jtable(){
        tblClientes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblClientes.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblClientes.getColumnModel().getColumn(1).setPreferredWidth(304);
        tblClientes.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblClientes.getColumnModel().getColumn(3).setPreferredWidth(110);
    }
    
    //MÉTODO QUE POPULA A COMBOBOX COM OS DADOS DO BANCO DE DADOS
    public void readComboUf(){
        EstadoDAO estadodao = new EstadoDAO();
        for(Estado estado: estadodao.read()){         
            ComboUF.addItem(estado.getUf());
        };
    }
    
    //MÉTODO QUE VERIFICA O CEP E SE TIVER NO WEBSERVICE PREENCHE OS CAMPOS
    public void Verifica_Cep(){
        if(txtEndereco.requestFocus(true)){
             WebServiceCep webservicecep = WebServiceCep.searchCep(jftxtCep.getText());
            
             if(webservicecep.wasSuccessful()){
                ComboUF.setSelectedItem(webservicecep.getUf());
                txtCidade.setText(webservicecep.getCidade());
                txtEndereco.setText(webservicecep.getLogradouro());
                txtNumero.requestFocus();
            }else{

            }
        }
    }
    
    //MÉTODO QUE DESATIVA TODOS OS CAMPOS DA TELA
    public void desativa_Campos(){
        txtNome.setEnabled(false);
        comboPessoa.setEnabled(false);
        jftxtData_Nasc.setEnabled(false);
        jftxtRg.setEnabled(false);
        jftxtCpf.setEnabled(false);
        jftxtCnpj.setEnabled(false);
        ComboSexo.setEnabled(false);
        jftxtTelFixo.setEnabled(false);
        jftxtTelCel.setEnabled(false);
        txtContato.setEnabled(false);
        txtEmail.setEnabled(false);
        jftxtCep.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNumero.setEnabled(false);
        ComboUF.setEnabled(false);
        txtCidade.setEnabled(false);
        txtComplemento.setEnabled(false);
    }
    
    //MÉTODO QUE ATIVA TODOS OS CAMPOS DA TELA
    public void ativa_Campos(){
        txtNome.setEnabled(true);
        comboPessoa.setEnabled(true);
        jftxtData_Nasc.setEnabled(true);
        jftxtRg.setEnabled(true);
        jftxtCpf.setEnabled(true);
        jftxtCnpj.setEnabled(true);
        ComboSexo.setEnabled(true);
        jftxtTelFixo.setEnabled(true);
        jftxtTelCel.setEnabled(true);
        txtContato.setEnabled(true);
        txtEmail.setEnabled(true);
        jftxtCep.setEnabled(true);
        txtEndereco.setEnabled(true);
        txtNumero.setEnabled(true);
        ComboUF.setEnabled(true);
        txtCidade.setEnabled(true);
        txtComplemento.setEnabled(true);
    }
    
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        Cliente cliente = new Cliente();
        ClienteDAO clientedao = new ClienteDAO();

        ativa_Campos();
        txtNome.requestFocus();
        flag = 1;
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(false);
        tblClientes.setVisible(false);
        btnCancelar.setEnabled(true);

        Verifica_Pessoa();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if((tblClientes.getSelectedRow() != -1)){
            Cliente cliente = new Cliente();
            ClienteDAO clientedao = new ClienteDAO();

            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?",getTitle(),+ JOptionPane.YES_NO_OPTION);

            if(resposta==JOptionPane.YES_OPTION){
                cliente.setId((int)tblClientes.getValueAt(tblClientes.getSelectedRow(),0));

                clientedao.delete(cliente);
                readJTable();
                Limpa_Campos();
                tblClientes.clearSelection();
                btnExcluir.setEnabled(false);
                btnSalvar.setEnabled(false);
                btnCancelar.setEnabled(false);
            }else{
                tblClientes.clearSelection();
                btnExcluir.setEnabled(false);
                btnSalvar.setEnabled(false);
                btnCancelar.setEnabled(false);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Selecione um cliente!");
        }
        btnNovo.setEnabled(true);
        comboPessoa.setSelectedIndex(0);
        desativa_Campos();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if(flag == 2){//SE NA BANDEIRA ESTIVER MARCADO 2 SIGNIFICA QUE O USUÁRIO ESTÁ ALTERANDO DADOS DOS CLIENTES
            if((tblClientes.getSelectedRow() != -1)){
                Cliente cliente = new Cliente();
                ClienteDAO clientedao = new ClienteDAO();

                //VALIDA SE O NOME É ESPAÇO EM BRANCO SE FOR ELE DA A MENSAGEM QUE O CAMPO NOME PRECISA SER PREENCHIDO
                if(txtNome.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "O Campo nome precisa ser preenchido!");

                    if(pnlGuias.getSelectedIndex()==1){
                        pnlGuias.setSelectedIndex(0);
                        txtNome.requestFocus();
                    }else{
                        txtNome.requestFocus();
                    }

                }else{
                    cliente.setNome(txtNome.getText());
                    cliente.setTipoPessoa(String.valueOf(comboPessoa.getSelectedItem()));
                    cliente.setData_nasc(jftxtData_Nasc.getText());
                    cliente.setCpf(jftxtCpf.getText());
                    cliente.setCnpj(jftxtCnpj.getText());
                    cliente.setRg(jftxtRg.getText());

                    //VALIDANDO SE O SEXO É MASCULINO OU FEMININO - SE NAO FOR NENHUM DOS DOIS ELE GRAVA NO BANCO UM ESPAÇO NULO
                    if((ComboSexo.getSelectedIndex()==0)){
                        cliente.setSexo("");
                    }else{
                        cliente.setSexo(String.valueOf(ComboSexo.getSelectedItem()));
                    }

                    cliente.setTel_fixo(jftxtTelFixo.getText());
                    cliente.setTel_cel(jftxtTelCel.getText());
                    cliente.setEmail(txtEmail.getText());
                    cliente.setCep(jftxtCep.getText());
                    cliente.setEndereco(txtEndereco.getText());

                    //VALIDANDO SE O NÚMERO FOR NULL ELE GRAVA NO BANCO NUMERO 0
                    if(txtNumero.getText().equals("")){
                        txtNumero.setText("0");
                    }else{
                        cliente.setNumero(Integer.parseInt(txtNumero.getText()));
                    }

                    //VALIDANDO QUAL É O ESTADO - SE NAO FOR NENHUM DOS ESTADOS ELE GRAVA NO BANCO UM ESPAÇO NULO
                    if((ComboUF.getSelectedIndex()==0)){
                        cliente.setUf("");
                    }else{
                        cliente.setUf(String.valueOf(ComboUF.getSelectedItem()));
                    }

                    cliente.setCidade(txtCidade.getText());
                    cliente.setComplemento(txtComplemento.getText());
                    cliente.setId((int)tblClientes.getValueAt(tblClientes.getSelectedRow(),0));

                    clientedao.update(cliente); //CHAMA O MÉTODO QUE FAZ O UPDATE NO BANCO DE DADOS
                    readJTable();
                    Limpa_Campos();
                    btnNovo.setEnabled(true);
                    btnSalvar.setEnabled(false);
                    btnExcluir.setEnabled(false);
                    btnCancelar.setEnabled(false);
                    tblClientes.clearSelection();//RETIRA A SELEÇÃO DA TABELA
                    comboPessoa.setSelectedIndex(0);
                    pnlGuias.setSelectedIndex(0);
                    desativa_Campos();//DESATIVA OS CAMPOS DA TABELA
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Selecione um cliente!");
            }
        }else{//SE NA BANDEIRA ESTIVER MARCADO 1 SIGNIFICA QUE O USUÁRIO ESTÁ INSERINDO NO BANCO DE DADOS UM NOVO CLIENTE
            Cliente cliente = new Cliente();
            ClienteDAO clientedao = new ClienteDAO();

            //VALIDA SE O NOME É ESPAÇO EM BRANCO SE FOR ELE DA A MENSAGEM QUE O CAMPO NOME PRECISA SER PREENCHIDO
            if(txtNome.getText().equals("")){
                JOptionPane.showMessageDialog(null, "O Campo nome precisa ser preenchido!");

                if(pnlGuias.getSelectedIndex()==1){
                    pnlGuias.setSelectedIndex(0);
                    txtNome.requestFocus();
                }else{
                    txtNome.requestFocus();
                }

            }else{
                cliente.setNome(txtNome.getText());
                cliente.setTipoPessoa(String.valueOf(comboPessoa.getSelectedItem()));
                cliente.setData_nasc(jftxtData_Nasc.getText());
                cliente.setRg(jftxtRg.getText());
                cliente.setCpf(jftxtCpf.getText());
                cliente.setCnpj(jftxtCnpj.getText());

                //VALIDANDO SE O SEXO É MASCULINO OU FEMININO - SE NAO FOR NENHUM DOS DOIS ELE GRAVA NO BANCO UM ESPAÇO NULO
                if((ComboSexo.getSelectedIndex()==0)){
                    cliente.setSexo("");
                }else{
                    cliente.setSexo(String.valueOf(ComboSexo.getSelectedItem()));
                }

                cliente.setTel_fixo(jftxtTelFixo.getText());
                cliente.setTel_cel(jftxtTelCel.getText());
                cliente.setEmail(txtEmail.getText());
                cliente.setCep(jftxtCep.getText());
                cliente.setEndereco(txtEndereco.getText());

                //VALIDANDO SE O NÚMERO FOR NULL ELE GRAVA NO BANCO NUMERO 0
                if(txtNumero.getText().equals("")){
                    txtNumero.setText("0");
                }else{
                    cliente.setNumero(Integer.parseInt(txtNumero.getText()));
                }

                //VALIDANDO QUAL É O ESTADO - SE NAO FOR NENHUM DOS ESTADOS ELE GRAVA NO BANCO UM ESPAÇO NULO
                if((ComboUF.getSelectedIndex()==0)){
                    cliente.setUf("");
                }else{
                    cliente.setUf(String.valueOf(ComboUF.getSelectedItem()));
                }

                cliente.setCidade(txtCidade.getText());
                cliente.setComplemento(txtComplemento.getText());

                clientedao.create(cliente);//CHAMA O MÉTODO QUE FAZ A INSERÇÃO NO BANCO DE DADOS
                Limpa_Campos();
                readJTable();
                btnNovo.setEnabled(true);
                btnSalvar.setEnabled(false);
                btnExcluir.setEnabled(false);
                btnCancelar.setEnabled(false);
                tblClientes.setVisible(true);
                tblClientes.clearSelection();//RETIRA A SELEÇÃO DA TABELA
                comboPessoa.setSelectedIndex(0);
                pnlGuias.setSelectedIndex(0);
                desativa_Campos();//DESATIVA OS CAMPOS DA TABELA
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Limpa_Campos();
        comboPessoa.setSelectedIndex(0);
        pnlGuias.setSelectedIndex(0);
        desativa_Campos();
        btnExcluir.setEnabled(true);
        flag = -1;
        tblClientes.setVisible(true);
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        tblClientes.clearSelection();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAvançarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvançarActionPerformed
        pnlGuias.setSelectedIndex(1);
    }//GEN-LAST:event_btnAvançarActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeKeyPressed

    private void ComboSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboSexoActionPerformed

    private void jftxtTelCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxtTelCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxtTelCelActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jftxtCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxtCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxtCnpjActionPerformed

    private void comboPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPessoaActionPerformed
        Verifica_Pessoa();
    }//GEN-LAST:event_comboPessoaActionPerformed

    private void txtContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContatoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        pnlGuias.setSelectedIndex(0);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jftxtCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftxtCepFocusLost

        WebServiceCep webservicecep = WebServiceCep.searchCep(jftxtCep.getText());
        if(webservicecep.wasSuccessful()){
            ComboUF.setSelectedItem(webservicecep.getUf());
            txtCidade.setText(webservicecep.getCidade());
            txtEndereco.setText(webservicecep.getLogradouro());
        }else{

        }
    }//GEN-LAST:event_jftxtCepFocusLost

    private void jftxtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxtCepActionPerformed

    }//GEN-LAST:event_jftxtCepActionPerformed

    private void jftxtCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftxtCepKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            WebServiceCep webservicecep = WebServiceCep.searchCep(jftxtCep.getText());
            if(webservicecep.wasSuccessful()){
                ComboUF.setSelectedItem(webservicecep.getUf());
                txtCidade.setText(webservicecep.getCidade());
                txtEndereco.setText(webservicecep.getLogradouro());
            }else{

            }
        }
    }//GEN-LAST:event_jftxtCepKeyPressed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        if(tblClientes.getSelectedRow() != -1){
            Limpa_Campos();
            ClienteDAO clientedao = new ClienteDAO();
            flag = 2;

            ativa_Campos();

            int id = (int) tblClientes.getValueAt(tblClientes.getSelectedRow(),0);

            for(Cliente cliente: clientedao.read_Method(id)){

                txtNome.setText(cliente.getNome());
                comboPessoa.setSelectedItem(String.valueOf(cliente.getTipoPessoa()));
                jftxtData_Nasc.setText(cliente.getData_nasc());
                jftxtRg.setText(cliente.getRg());
                jftxtCpf.setText(cliente.getCpf());
                jftxtCnpj.setText(cliente.getCnpj());
                ComboSexo.setSelectedItem(String.valueOf(cliente.getSexo()));
                jftxtTelFixo.setText(cliente.getTel_fixo());
                jftxtTelCel.setText(cliente.getTel_cel());
                txtEmail.setText(cliente.getEmail());
                jftxtCep.setText(cliente.getCep());
                txtEndereco.setText(cliente.getEndereco());
                txtNumero.setText(String.valueOf(cliente.getNumero()));
                ComboUF.setSelectedItem(String.valueOf(cliente.getUf()));
                txtCidade.setText(cliente.getCidade());
                txtComplemento.setText(cliente.getComplemento());

            }
            btnNovo.setEnabled(false);
            btnSalvar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnCancelar.setEnabled(true);

        }

    }//GEN-LAST:event_tblClientesMouseClicked

    private void tblClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblClientesKeyPressed
        if(tblClientes.getSelectedRow() != -1){
            Limpa_Campos();

            ClienteDAO clientedao = new ClienteDAO();
            flag = 2;

            ativa_Campos();

            int id = (int) tblClientes.getValueAt(tblClientes.getSelectedRow(),0);

            for(Cliente cliente: clientedao.read_Method(id)){

                txtNome.setText(cliente.getNome());
                comboPessoa.setSelectedItem(String.valueOf(cliente.getTipoPessoa()));
                jftxtData_Nasc.setText(cliente.getData_nasc());
                jftxtRg.setText(cliente.getRg());
                jftxtCpf.setText(cliente.getCpf());
                jftxtCnpj.setText(cliente.getCnpj());
                ComboSexo.setSelectedItem(String.valueOf(cliente.getSexo()));
                jftxtTelFixo.setText(cliente.getTel_fixo());
                jftxtTelCel.setText(cliente.getTel_cel());
                txtEmail.setText(cliente.getEmail());
                jftxtCep.setText(cliente.getCep());
                txtEndereco.setText(cliente.getEndereco());
                txtNumero.setText(String.valueOf(cliente.getNumero()));
                ComboUF.setSelectedItem(String.valueOf(cliente.getUf()));
                txtCidade.setText(cliente.getCidade());
                txtComplemento.setText(cliente.getComplemento());

            }
            btnNovo.setEnabled(false);
            btnSalvar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnCancelar.setEnabled(true);

        }
    }//GEN-LAST:event_tblClientesKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboSexo;
    private javax.swing.JComboBox<String> ComboUF;
    private javax.swing.JButton btnAvançar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> comboPessoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jftxtCep;
    private javax.swing.JFormattedTextField jftxtCnpj;
    private javax.swing.JFormattedTextField jftxtCpf;
    private javax.swing.JFormattedTextField jftxtData_Nasc;
    private javax.swing.JFormattedTextField jftxtPesquisa;
    private javax.swing.JFormattedTextField jftxtRg;
    private javax.swing.JFormattedTextField jftxtTelCel;
    private javax.swing.JFormattedTextField jftxtTelFixo;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblClientesCadastrados;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblData_Nasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPessoa;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelCel;
    private javax.swing.JLabel lblTelFixo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUF;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelDadosp;
    private javax.swing.JPanel painelDadosr;
    private javax.swing.JPanel painelTabela;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JTabbedPane pnlGuias;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
