/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Web_Service_CEP.WebServiceCep;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.dao.EstadoDAO;
import model.dao.FuncionarioDAO;
import model.dao.QuartoDAO;
import model.pojo.Estado;
import model.pojo.Funcionario;
import model.pojo.Quarto;

/**
 *
 * @author Usuario
 */
public class Gerenciamento_de_Quartos extends javax.swing.JInternalFrame {
    int flag = -1;
    /**
     * Creates new form Cadastro_de_Funcionarios
     */
    public Gerenciamento_de_Quartos() {
        initComponents();
        seta_Botoes();
        readJTable();
        desativa_Campos();
    }

    
    //MÉTODO QUE LIMPA TODOS OS CAMPOS DA TELA DE CADASTRO
    public void Limpa_Campos(){
        txtDescricao.setText("");
        txtAndar.setText("");
        txtValDiaria.setText("");
        txtPesquisa.setText("");
    }
    
    //MÉTODO PARA HABILITAR OU DESABILITAR BOTÕES
    public void seta_Botoes(){
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
    }
    
    //MÉTODO QUE POPULA A TABELA DE QUARTOS COM OS DADOS DO BANCO DE DADOS
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) tblQuartos.getModel();
        modelo.setNumRows(0);
        QuartoDAO quartodao = new QuartoDAO();
        
        for(Quarto quarto: quartodao.read()){
            modelo.addRow(new Object[]{
                quarto.getId_quarto(),
                quarto.getDescricao(),
                quarto.getAndar(),
                quarto.getVal_diaria()
            });
        }
        SetaLargura_Jtable();
    }
    
    //MÉTODO QUE SETA A LARGURA DOS CAMPOS DA TABELA DOS CLIENTES
    public void SetaLargura_Jtable(){
        tblQuartos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblQuartos.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblQuartos.getColumnModel().getColumn(1).setPreferredWidth(304);
        tblQuartos.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblQuartos.getColumnModel().getColumn(3).setPreferredWidth(110);
    }
    
    //MÉTODO QUE DESATIVA TODOS OS CAMPOS DA TELA
    public void desativa_Campos(){
        txtDescricao.setEnabled(false);
        txtAndar.setEnabled(false);
        txtValDiaria.setEnabled(false);
        txtPesquisa.setEnabled(false);
        txtApartamento.setEnabled(false);
        chbAtivo.setEnabled(false);
        chbInativo.setEnabled(false);
    }
    
    //MÉTODO QUE ATIVA TODOS OS CAMPOS DA TELA
    public void ativa_Campos(){
        txtDescricao.setEnabled(true);
        txtAndar.setEnabled(true);
        txtValDiaria.setEnabled(true);
        txtPesquisa.setEnabled(true);
        txtApartamento.setEnabled(true);
        chbAtivo.setEnabled(false);
        chbInativo.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBtnAtIn = new javax.swing.ButtonGroup();
        painelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlGuias = new javax.swing.JTabbedPane();
        painelDadosp = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblAndar = new javax.swing.JLabel();
        lblValDiaria = new javax.swing.JLabel();
        txtValDiaria = new javax.swing.JTextField();
        txtAndar = new javax.swing.JTextField();
        lblApartamento = new javax.swing.JLabel();
        txtApartamento = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        chbAtivo = new javax.swing.JCheckBox();
        chbInativo = new javax.swing.JCheckBox();
        painelTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuartos = new javax.swing.JTable();
        lblQuartosCadastrados = new javax.swing.JLabel();
        lblPesquisa = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        painelBotoes = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Funcionários");

        painelTitulo.setBackground(new java.awt.Color(204, 204, 204));
        painelTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelTitulo.setOpaque(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblTitulo.setText("Gerenciamento de Quartos");

        javax.swing.GroupLayout painelTituloLayout = new javax.swing.GroupLayout(painelTitulo);
        painelTitulo.setLayout(painelTituloLayout);
        painelTituloLayout.setHorizontalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelTituloLayout.setVerticalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblTitulo))
        );

        pnlGuias.setBackground(new java.awt.Color(204, 204, 204));
        pnlGuias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlGuias.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        painelDadosp.setBackground(new java.awt.Color(204, 204, 204));
        painelDadosp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelDadosp.setOpaque(false);
        painelDadosp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDescricao.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblDescricao.setText("Descrição: ");
        painelDadosp.add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtDescricao.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtDescricao.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        txtDescricao.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        painelDadosp.add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 530, 30));

        lblAndar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblAndar.setText("Andar: ");
        painelDadosp.add(lblAndar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lblValDiaria.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblValDiaria.setText("Valor diária:");
        painelDadosp.add(lblValDiaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        txtValDiaria.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtValDiaria.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        txtValDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValDiariaActionPerformed(evt);
            }
        });
        painelDadosp.add(txtValDiaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 160, 30));

        txtAndar.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtAndar.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        txtAndar.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtAndar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAndarActionPerformed(evt);
            }
        });
        painelDadosp.add(txtAndar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 30));

        lblApartamento.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblApartamento.setText("Apartamento: ");
        painelDadosp.add(lblApartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        txtApartamento.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtApartamento.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        txtApartamento.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtApartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApartamentoActionPerformed(evt);
            }
        });
        painelDadosp.add(txtApartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 150, 30));

        btnExcluir.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        painelDadosp.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 70, -1));

        btnSalvar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        painelDadosp.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        GrupoBtnAtIn.add(chbAtivo);
        chbAtivo.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        chbAtivo.setText("Ativo");
        painelDadosp.add(chbAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        GrupoBtnAtIn.add(chbInativo);
        chbInativo.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        chbInativo.setText("Inativo");
        painelDadosp.add(chbInativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        pnlGuias.addTab("Cadastro de Quartos", painelDadosp);

        painelTabela.setBackground(new java.awt.Color(255, 255, 255));
        painelTabela.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        painelTabela.setOpaque(false);

        tblQuartos.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        tblQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Descrição", "Andar", "Val. Diária", "Apartamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQuartos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuartosMouseClicked(evt);
            }
        });
        tblQuartos.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tblQuartosInputMethodTextChanged(evt);
            }
        });
        tblQuartos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblQuartosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblQuartos);

        lblQuartosCadastrados.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        lblQuartosCadastrados.setText("Quartos Cadastrados");

        lblPesquisa.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        lblPesquisa.setText("Pesquisa: ");

        txtPesquisa.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        txtPesquisa.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtPesquisa.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.UIManager.getDefaults().getColor("Button.light"), javax.swing.UIManager.getDefaults().getColor("Button.light")));
        txtPesquisa.setDisabledTextColor(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelTabelaLayout = new javax.swing.GroupLayout(painelTabela);
        painelTabela.setLayout(painelTabelaLayout);
        painelTabelaLayout.setHorizontalGroup(
            painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painelTabelaLayout.createSequentialGroup()
                .addComponent(lblQuartosCadastrados)
                .addGap(90, 90, 90)
                .addComponent(lblPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa)
                .addContainerGap())
        );
        painelTabelaLayout.setVerticalGroup(
            painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTabelaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuartosCadastrados)
                    .addComponent(lblPesquisa)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelBotoes.setBackground(new java.awt.Color(204, 204, 204));
        painelBotoes.setOpaque(false);

        btnSair.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlGuias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelTabela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGuias, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblQuartosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuartosMouseClicked
        if(tblQuartos.getSelectedRow() != -1){
            Limpa_Campos();
            QuartoDAO quartodao = new QuartoDAO();

            flag = 2;

            ativa_Campos();

            int id = (int) tblQuartos.getValueAt(tblQuartos.getSelectedRow(),0);

            for(Quarto quarto:quartodao.read_Method(id)){
                txtDescricao.setText(quarto.getDescricao());
                txtAndar.setText(String.valueOf(quarto.getAndar()));
                txtValDiaria.setText(String.valueOf(quarto.getVal_diaria()));
                txtApartamento.setText(String.valueOf(quarto.getId_quarto()));
                
                if(quarto.getQuarto_status()==1){
                    chbAtivo.setSelected(true);
                }else if(quarto.getQuarto_status()==0){
                    chbInativo.setSelected(true);
                }
            }
            txtAndar.setEditable(false);
            txtApartamento.setEditable(false);
            chbAtivo.setEnabled(true);
            chbInativo.setEnabled(true);
            
            btnSalvar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnCancelar.setEnabled(true);

        }

    }//GEN-LAST:event_tblQuartosMouseClicked

    private void tblQuartosInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tblQuartosInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tblQuartosInputMethodTextChanged

    private void tblQuartosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblQuartosKeyPressed
        if(tblQuartos.getSelectedRow() != -1){
            Limpa_Campos();

            QuartoDAO quartodao = new QuartoDAO();
            flag = 2;

            ativa_Campos();

            int id = (int) tblQuartos.getValueAt(tblQuartos.getSelectedRow(),0);

            for(Quarto quarto:quartodao.read_Method(id)){
                txtDescricao.setText(quarto.getDescricao());
                txtAndar.setText(String.valueOf(quarto.getAndar()));
                txtValDiaria.setText(String.valueOf(quarto.getVal_diaria()));
            }
            btnSalvar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnCancelar.setEnabled(true);

        }
    }//GEN-LAST:event_tblQuartosKeyPressed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if((tblQuartos.getSelectedRow() != -1)){
            Quarto quarto = new Quarto();
            QuartoDAO quartodao = new QuartoDAO();

            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?",getTitle(),+ JOptionPane.YES_NO_OPTION);

            if(resposta==JOptionPane.YES_OPTION){
                quarto.setId_quarto((int)tblQuartos.getValueAt(tblQuartos.getSelectedRow(),0));

                quartodao.delete(quarto);
                readJTable();
                Limpa_Campos();
                tblQuartos.clearSelection();
                btnExcluir.setEnabled(false);
                btnSalvar.setEnabled(false);
                btnCancelar.setEnabled(false);
            }else{
                tblQuartos.clearSelection();
                btnExcluir.setEnabled(false);
                btnSalvar.setEnabled(false);
                btnCancelar.setEnabled(false);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Selecione um funcionário!");
        }
        desativa_Campos();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if(flag == 2){//SE NA BANDEIRA ESTIVER MARCADO 2 SIGNIFICA QUE O USUÁRIO ESTÁ ALTERANDO DADOS DOS QUARTOS
            if((tblQuartos.getSelectedRow() != -1)){
                Quarto quarto = new Quarto();
                QuartoDAO quartodao = new QuartoDAO();

                //VALIDA SE A DESCRIÇÃO É ESPAÇO EM BRANCO SE FOR ELE DA A MENSAGEM QUE O CAMPO NOME PRECISA SER PREENCHIDO
                if(txtDescricao.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "O Campo descrição precisa ser preenchido!");
                }
                else{
                    quarto.setDescricao(txtDescricao.getText());
                    quarto.setAndar(Integer.valueOf(txtAndar.getText()));
                    quarto.setVal_diaria(Double.parseDouble(txtValDiaria.getText()));
                    
                    if(chbAtivo.isSelected()){
                        quarto.setQuarto_status(1);
                    }else if(chbInativo.isSelected()){
                        quarto.setQuarto_status(0);
                    }
                    
                    quarto.setId_quarto((int)tblQuartos.getValueAt(tblQuartos.getSelectedRow(),0));

                    quartodao.update(quarto); //CHAMA O MÉTODO QUE FAZ O UPDATE NO BANCO DE DADOS
                    readJTable();
                    Limpa_Campos();
                    btnSalvar.setEnabled(false);
                    btnExcluir.setEnabled(false);
                    btnCancelar.setEnabled(false);
                    tblQuartos.clearSelection();//RETIRA A SELEÇÃO DA TABELA
                    desativa_Campos();//DESATIVA OS CAMPOS DA TABELA
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Selecione um quarto!");
            }
        }else{//SE NA BANDEIRA ESTIVER MARCADO 1 SIGNIFICA QUE O USUÁRIO ESTÁ INSERINDO NO BANCO DE DADOS UM NOVO QUARTO
           Quarto quarto = new Quarto();
           QuartoDAO quartodao = new QuartoDAO();
            //VALIDA SE O NOME É ESPAÇO EM BRANCO SE FOR ELE DA A MENSAGEM QUE O CAMPO DESCRIÇÃO PRECISA SER PREENCHIDO
            if(txtDescricao.getText().equals("")){
                JOptionPane.showMessageDialog(null, "O Campo descrição recisa ser preenchido!");
            }else{
                quarto.setDescricao(txtDescricao.getText());
                quarto.setAndar(Integer.valueOf(txtAndar.getText()));
                quarto.setVal_diaria(Double.parseDouble(txtValDiaria.getText()));

                quartodao.create(quarto);//CHAMA O MÉTODO QUE FAZ A INSERÇÃO NO BANCO DE DADOS
                Limpa_Campos();
                readJTable();
                btnSalvar.setEnabled(false);
                btnExcluir.setEnabled(false);
                btnCancelar.setEnabled(false);
                tblQuartos.setVisible(true);
                tblQuartos.clearSelection();//RETIRA A SELEÇÃO DA TABELA
                desativa_Campos();//DESATIVA OS CAMPOS DA TABELA
            }
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Limpa_Campos();
        desativa_Campos();
        btnExcluir.setEnabled(true);
        flag = -1;
        tblQuartos.setVisible(true);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        tblQuartos.clearSelection();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtAndarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAndarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAndarActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApartamentoActionPerformed

    private void txtValDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValDiariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValDiariaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoBtnAtIn;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chbAtivo;
    private javax.swing.JCheckBox chbInativo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAndar;
    private javax.swing.JLabel lblApartamento;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblQuartosCadastrados;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValDiaria;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelDadosp;
    private javax.swing.JPanel painelTabela;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JTabbedPane pnlGuias;
    private javax.swing.JTable tblQuartos;
    private javax.swing.JTextField txtAndar;
    private javax.swing.JTextField txtApartamento;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtValDiaria;
    // End of variables declaration//GEN-END:variables
}
