package view;

import ds.desktop.notify.DesktopNotify;
import java.awt.Dimension;
import java.awt.Toolkit;
import model.dao.BemVindoDAO;
import model.dao.FuncionarioDAO;
import model.pojo.BemVindo;
import model.pojo.Funcionario;

/**
 *
 * @author Ebner Silva
 */
public class Tela_de_Login extends javax.swing.JFrame {
    public Tela_de_Login() {
        initComponents();
    }

    //MÉTODO QUE AJUSTA A RESOLUÇÃO NA TELA INICIAL
    public static void ajustaResolucao(Tela_Inicial tela){
        Toolkit kit = Toolkit.getDefaultToolkit();  
        Dimension tamTela = kit.getScreenSize();  

        //Pega largura e altura da tela 
        int larg = tamTela.width;  
        int alt = tamTela.height-30;  

        /* larg x 0.7; para ocupar 70% da tela por exemplo  */  
        /* alt x 0.7;*/  

        //Manda o JFrame utilizar suas dimensões  
        tela.setSize(larg,alt);
    }
    
    public void acao_btnAcessar(){
        FuncionarioDAO funcionariodao = new FuncionarioDAO();
        Funcionario funcionario = new Funcionario();
        BemVindoDAO bemvindodao = new BemVindoDAO();
        
        if(txtLogin.getText().equals("")){
            //JOptionPane.showMessageDialog(null, "O Campo Login necessita ser preenchido! ","Atençao!",JOptionPane.ERROR_MESSAGE);
            DesktopNotify.showDesktopMessage("Atenção!", "O Campo Usuário necessita ser preenchido!",DesktopNotify.ERROR,5000L);
            txtLogin.requestFocus();
        }
            else if(jptxtSenha.getText().equals("")){
                //JOptionPane.showMessageDialog(null, "O Campo Senha necessita ser preenchido! ","Atençao!",JOptionPane.ERROR_MESSAGE);
                DesktopNotify.showDesktopMessage("Atenção!", "O Campo Senha necessita ser preenchido!",DesktopNotify.ERROR,5000L);
                jptxtSenha.requestFocus();
            }else if(bemvindodao.read_Login(txtLogin.getText(),jptxtSenha.getText())){
                Tela_Inicial tela_inicial = new Tela_Inicial();
                tela_inicial.setVisible(true);
                dispose();
                DesktopNotify.showDesktopMessage("Acesso Liberado!", "Bem vindo ao Sistema Diretoria Hotéis!",DesktopNotify.SUCCESS,5000L);
            } 
                else if(funcionariodao.read_Login(txtLogin.getText(),jptxtSenha.getText())==true){
                    Tela_Inicial tela_inicial = new Tela_Inicial();
                    tela_inicial.setVisible(true);
                    dispose();
                    DesktopNotify.showDesktopMessage("Acesso Liberado!", "Bem vindo ao Sistema Diretoria Hotéis!",DesktopNotify.SUCCESS,5000L);
        }else{
            //JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos!","Login Inválido!",JOptionPane.ERROR_MESSAGE);
            DesktopNotify.showDesktopMessage("Login Inválido!", "Usuário ou senha incorretos!",DesktopNotify.ERROR,5000L);
            txtLogin.setText("Digite seu Usuário");
            jptxtSenha.setText("Digite sua Senha");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBemVindo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCopiryght = new javax.swing.JLabel();
        painelLogin = new javax.swing.JPanel();
        btnAcessar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        jptxtSenha = new javax.swing.JPasswordField();
        txtLogin = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Hotéis - Diretoria - v1.0");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        painelBemVindo.setBackground(new java.awt.Color(49, 58, 115));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seja Bem Vindo ao Diretoria Hotéis");

        lblCopiryght.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblCopiryght.setForeground(new java.awt.Color(255, 255, 255));
        lblCopiryght.setText("Diretoria -  Todos os Direitos Reservados");

        javax.swing.GroupLayout painelBemVindoLayout = new javax.swing.GroupLayout(painelBemVindo);
        painelBemVindo.setLayout(painelBemVindoLayout);
        painelBemVindoLayout.setHorizontalGroup(
            painelBemVindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBemVindoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBemVindoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCopiryght)
                .addGap(39, 39, 39))
        );
        painelBemVindoLayout.setVerticalGroup(
            painelBemVindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBemVindoLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCopiryght, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelLogin.setBackground(new java.awt.Color(255, 255, 255));

        btnAcessar.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        btnAcessar.setText("Acessar");
        btnAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        lblUsuario.setText("Usuário: ");

        lblSenha.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        lblSenha.setText("Senha: ");

        jptxtSenha.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jptxtSenha.setText("Digite sua senha");
        jptxtSenha.setToolTipText("");
        jptxtSenha.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jptxtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jptxtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jptxtSenhaFocusLost(evt);
            }
        });

        txtLogin.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        txtLogin.setText("Digite seu Usuário");
        txtLogin.setToolTipText("");
        txtLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        txtLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLoginFocusLost(evt);
            }
        });

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addComponent(btnAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtLogin)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jptxtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblSenha)
                .addGap(0, 0, 0)
                .addComponent(jptxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcessar)
                    .addComponent(btnSair))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(painelBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarActionPerformed
        acao_btnAcessar();
    }//GEN-LAST:event_btnAcessarActionPerformed

    private void txtLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginFocusGained
        txtLogin.setText("");
    }//GEN-LAST:event_txtLoginFocusGained

    private void jptxtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jptxtSenhaFocusGained
        jptxtSenha.setText("");
    }//GEN-LAST:event_jptxtSenhaFocusGained

    private void jptxtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jptxtSenhaFocusLost
        if(jptxtSenha.getText().equals("")){
            jptxtSenha.setText("Digite sua senha");
        }
    }//GEN-LAST:event_jptxtSenhaFocusLost

    private void txtLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginFocusLost
        if(txtLogin.getText().equals("")){
            txtLogin.setText("Digite seu Usuário");
        }
    }//GEN-LAST:event_txtLoginFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        painelLogin.requestFocus();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BemVindoDAO bvd = new BemVindoDAO();
                if(bvd.readStatusHotel()==1){
                    new Tela_de_Login().setVisible(true);
                }else{
                    new Tela_de_Bem_Vindo().setVisible(true);
                }
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField jptxtSenha;
    private javax.swing.JLabel lblCopiryght;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel painelBemVindo;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables
}
